import bg from "@/assets/bg/1.avif";
import Providers from "@/providers";
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";
import "./style.css";
import "react-tooltip/dist/react-tooltip.css";
import SettingsTrigger from "@/components/settings/settings-trigger";
import SettingsMenu from "@/components/settings/settings-menu";
import ThemeProvider from "@/components/theme-provider";
import SettingsContent from "@/components/settings/settings-content";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-ctp-base overflow-hidden ">
          <ThemeProvider>
            {children}

            <Image
              src={bg}
              alt="bg"
              className="absolute inset-0 w-full h-full object-cover max-h-[100svh] max-w-[100svw]"
              fill
            />
            <div className="absolute top-0 md:left-0 right-0 z-10 ">
              <SettingsMenu>
                <SettingsContent />
              </SettingsMenu>
              <div className="md:p-4 md:px-4 px-4 py-8">
                <SettingsTrigger />
              </div>
            </div>
          </ThemeProvider>
        </body>
      </Providers>
    </html>
  );
}
